name: Bridgecrew
on:
  push:
    branches:
      - master
jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Run PrismaCloud   
      id: prisma-cloud
      uses: bridgecrewio/checkovaction@master 
      env:
        PRISMA_API_URL: https://api.sg.prismacloud.io
      with:
        api-key: ${{ secrets.BC_API_KEY }}
